EN-109: fix employees reporting
entropy-code/entropay-employees pull request #108
Opened 2023-10-19 17:52 UTC by FedericoA15

# Description :pencil:

Restriction is added for those who can see the reporting and filtering by role

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-109

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:
![image](https://github.com/entropy-code/entropay-employees/assets/96883646/9f854259-8ce0-4b7b-9f25-c610ecc1808a)
view according to the hr manager
![image](https://github.com/entropy-code/entropay-employees/assets/96883646/91364ac6-4ed2-4d49-9650-9c7fa0c93436)
view according to admin or HR director

2023-10-19 18:19 UTC, agustinb4 requested changes

2023-10-19 18:19 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/repositories/EmployeeRepository.java
> +
try with this:
```
@Query("SELECT e FROM Employee e INNER JOIN Role r " 
            + " WHERE e.deleted = false AND e.active = true AND lower(r.name) like lower('%HR%')")
    List<Employee> findAllNotHrEmployees();
```

2023-10-20 18:21 UTC, agustinb4 approved these changes
Good job!, just a minor comment

2023-10-20 18:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/auth/AuthUtil.java
> +public class AuthUtil {
It should be `AuthUtils`

2023-10-23 13:11 UTC, FedericoA15 commented on src/main/java/com/entropyteam/entropay/auth/AuthUtil.java
> +public class AuthUtil {
fixed

2023-10-23 13:58 UTC, merged