En 113
entropy-code/entropay-employees pull request #118
Opened 2023-11-14 18:48 UTC by FedericoA15

# Description :pencil:

Endpoint was created to synchronize existing birthdays in Google Calendar and when an employee is created it saves the birthday date

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-113

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

![image](https://github.com/entropy-code/entropay-employees/assets/96883646/62a968ed-49d4-462a-9aa4-e62041164416)

2023-11-14 19:48 UTC, jauday approved these changes

2023-11-15 12:53 UTC, agustinb4 requested changes

2023-11-15 12:53 UTC, agustinb4 commented on pom.xml
> +        <google-oauth-client-jetty>1.34.1</google-oauth-client-jetty>
not used

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/controllers/EmployeeController.java
> +    @GetMapping("/birthday")
minor, can we change the endpoint to /sync-birthday. Also the method name could be syncEmployeeBirthday

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +}
remove

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +    }
remove

2023-11-15 12:53 UTC, agustinb4 commented on src/test/java/com/entropyteam/entropay/employees/services/GoogleServiceTest.java
> +package com.entropyteam.entropay.employees.services;
remove test

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
> +    public void createGoogleCalendarEventsForBirthdays() throws IOException {
will this method create duplicates?

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +            String calendarId = "<Calender Id>";
this should be a env var

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
> +        googleService.createGoogleCalendarEvent("BirthDay " + employeeDto.firstName() + " " + employeeDto.lastName(), modifiedBirthDate, modifiedBirthDate);
minor, lets extract this lines in a method that receives a list of employees, create the event name then call google service

2023-11-15 12:53 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +            System.out.println("Event created: " + event.getHtmlLink());
use Logger

2023-11-15 14:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +    }
remove

2023-11-15 14:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +
avoid multiple convertions

2023-11-15 14:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +}
remove

2023-11-15 14:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +            e.printStackTrace();
fix with LOGGER.error(e.getMessage());

2023-11-23 15:48 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleCredentialsProperties.java
> +    private String secretClient;
remove

2023-11-23 15:48 UTC, agustinb4 commented on src/main/resources/application.properties
> +google-credentials.secret-client=''
remove

2023-11-27 12:21 UTC, agustinb4 approved these changes
Good Job man! some minors comments

2023-11-27 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
> +        String eventId = currentYear + "-" + employeeId.toString();
You are adding a "-" here, then replacing it for a blank space in the google service. Lets change to:
`String eventId = currentYear + employeeId.toString();`

2023-11-27 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/GoogleService.java
> +    }
you can change to:
   ```
 
    private static final Logger LOGGER = LogManager.getLogger();
    private static final JsonFactory JSON_FACTORY = GsonFactory.getDefaultInstance();
    private static final List<String> SCOPES = Collections.singletonList(CalendarScopes.CALENDAR);

    @Autowired
    private final GoogleCredentialsProperties googleCredentialsProperties;

```
removing the contructor

2023-11-27 16:11 UTC, merged