EN-136: Now pto days calculations takes into account employees country
entropy-code/entropay-employees pull request #141
Opened 2023-12-22 15:28 UTC by Paez99

# Description :pencil:

Added country as a mandatory field for employee creation
Now pto days calculations takes into account employees country
Added unit test

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

2023-12-22 15:44 UTC, FedericoA15 commented on src/main/java/com/entropyteam/entropay/employees/services/PtoService.java
> +import com.entropyteam.entropay.employees.repositories.*;
Minor changes in imports repositories

2023-12-27 15:42 UTC, FedericoA15 approved these changes
Good jon

2024-01-03 12:21 UTC, agustinb4 requested changes

2024-01-03 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/models/Employee.java
> +import javax.persistence.*;
please undo this import whit a *

2024-01-03 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/CountryService.java
> +import java.util.*;
Same, remove imports with *

2024-01-03 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/CountryService.java
> +        List<String> countries = countryRepository.findAllByDeletedIsFalseAndNameLikeIgnoreCase(ALL_COUNTRY_NAME).stream().map(Country::getName).toList();
minor: i think a better name could be: excluded countries

2024-01-03 12:21 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
> +    @Query(value = "SELECT hc.* FROM holiday_calendar AS hc INNER JOIN country AS c ON hc.country_id = c.id " +
why not use country id instead of name?

2024-01-03 12:59 UTC, Paez99 commented on src/main/java/com/entropyteam/entropay/employees/repositories/HolidayRepository.java
> +    @Query(value = "SELECT hc.* FROM holiday_calendar AS hc INNER JOIN country AS c ON hc.country_id = c.id " +
Changed it to country id

2024-01-04 14:24 UTC, agustinb4 approved these changes
Looks good

2024-01-04 14:36 UTC, merged