EN-141 Filter PTOs by year
entropy-code/entropay-employees pull request #149
Opened 2024-01-12 21:54 UTC by jauday

# Description :pencil:

This PR adds the possibility to filter PTOs by year considering start date and end date

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-141

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

Through the UI by creating Ptos and filtering
<img width="1430" alt="Screenshot 2024-01-12 at 18 13 53" src="https://github.com/entropy-code/entropay-admin-ui/assets/85446214/f1d92789-87f6-46d3-8538-fa9b9a1a6b36">
<img width="1429" alt="Screenshot 2024-01-12 at 18 14 05" src="https://github.com/entropy-code/entropay-admin-ui/assets/85446214/0cea38c5-51de-4399-ad8a-84b27e9b8efb">

<img width="1210" alt="Screenshot 2024-01-12 at 18 52 38" src="https://github.com/entropy-code/entropay-employees/assets/85446214/67a9e4ee-cc65-41c4-8fa2-896e0300339b">

2024-01-15 15:10 UTC, agustinb4 requested changes

2024-01-15 15:10 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/controllers/PtoController.java
> +import java.util.*;
:skull:

2024-01-15 15:10 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/controllers/PtoController.java
> +import org.springframework.web.bind.annotation.*;
:skull_and_crossbones:

2024-01-15 15:10 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
> +import com.entropyteam.entropay.employees.models.*;
:skull_and_crossbones:

2024-01-15 15:10 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/PtoService.java
> +import java.util.*;
:skull:

2024-06-25 16:20 UTC, eazaretzky commented
@jauday can you please solve the conflicts?

2024-07-16 01:11 UTC, eazaretzky requested changes
How does this solve the ticket? The base controller already handles the `from` and `to` parameter and the only thing needed from the BE was the list of years to be used by the FE?

2024-07-16 01:11 UTC, eazaretzky commented on src/main/java/com/entropyteam/entropay/employees/controllers/PtoController.java
> +import java.util.*;
please revert this change, it's better to have explicit imports to avoid importing unnecessary code

2024-07-16 01:11 UTC, eazaretzky commented on src/main/java/com/entropyteam/entropay/employees/repositories/PtoRepository.java
> +    List<Integer> getPtosYears();
It looks like an overly complicated way to get the years. Selecting the year of the first PTO should be enough

2024-07-16 13:10 UTC, closed without merging

2024-07-16 13:10 UTC, jauday commented
@eazaretzky I'm closing this. There was a misunderstood on ticket requirements at the beginning, no changes are required at the backend to make pto preset filters work.