EN-126: Time off reporting total by client
entropy-code/entropay-employees pull request #158
Opened 2024-02-08 15:25 UTC by Paez99

# Description :pencil:

Time off reporting total by client
Fixed bug on details by client and employee not filtering by year

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-126

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

2024-02-08 19:31 UTC, agustinb4 requested changes

2024-02-08 19:31 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
> +import java.util.*;
:skull_and_crossbones:

2024-02-08 19:31 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
> +                    .toList();
I think you can avoid these loops, we already have the employee id in the assignment

2024-02-09 12:02 UTC, Paez99 commented on src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
> +import java.util.*;
☠️

2024-02-09 12:40 UTC, agustinb4 approved these changes

2024-02-09 12:44 UTC, merged