EN-162: Displayed unassigned Client when group by Client
entropy-code/entropay-employees pull request #173
Opened 2024-03-08 11:40 UTC by Paez99

# Description :pencil:

In time off reporting those employees that do not have an assigned client now appear on the Gropy by Client under "No client" name.
Group by client detail is also working and shows the details of those ptos taken by employees without an assigned client

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-162

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:

![image](https://github.com/entropy-code/entropay-employees/assets/89614950/62833ad0-168a-4586-b8f7-1ed1a8dccba3)

2024-03-08 12:47 UTC, FacuOrellana commented on src/main/java/com/entropyteam/entropay/employees/services/EmployeeService.java
> +        List<Employee> fullEmployeesList = employeeRepository.findAllByDeletedIsFalseAndActiveIsTrue();
should we create a new repository method in order to replace all the operations in this method? @agustinb4

2024-03-15 14:51 UTC, agustinb4 requested changes

2024-03-15 14:51 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/services/ReportService.java
> +        List<PtoReportClientDto> ptosByClient = new ArrayList<>(clients.stream().map(client -> {
you can avoid de new ArrayList<>..

2024-03-26 11:41 UTC, agustinb4 approved these changes

2024-03-26 12:29 UTC, merged