End reason implementation for Contracts
entropy-code/entropay-employees pull request #244
Opened 2024-08-08 16:33 UTC by JoaFS

This pull request have the implementation of the end reasons of contracts.
I took the existing "Role" implementation as a reference to implement this new function.

2024-08-12 11:05 UTC, eazaretzky requested changes
only a few minor things to fix, good job!

2024-08-12 11:05 UTC, eazaretzky commented on src/main/java/com/entropyteam/entropay/employees/models/Contract.java
> +    public void setEndReason(EndReason endReason) { this.endReason = endReason; }
please fix format

2024-08-12 14:22 UTC, JoaFS commented on src/main/java/com/entropyteam/entropay/employees/dtos/EndReasonDto.java
> +    public EndReasonDto(EndReason endReason)    { this(endReason.getId(), endReason.getName());    }
Fixed

2024-08-12 14:22 UTC, JoaFS commented on src/main/java/com/entropyteam/entropay/employees/models/Contract.java
> +    public EndReason getEndReason() {  return endReason; }
Fixed

2024-08-12 14:24 UTC, JoaFS commented on src/main/java/com/entropyteam/entropay/employees/models/Contract.java
> +    public void setEndReason(EndReason endReason) { this.endReason = endReason; }
Fixed

2024-08-15 10:52 UTC, eazaretzky approved these changes

2024-08-15 10:52 UTC, eazaretzky commented on src/main/java/com/entropyteam/entropay/employees/services/ContractService.java
> +        contract.setEndReason(endReason);
@JoaFS another posible implementation of the same is this:
```
Optional.ofNullable(entity.endReasonId())
                .flatMap(endReasonRepository::findById)
                .ifPresent(contract::setEndReason);
```

Both are correct, I'm taking use of this opportunity just to show you some functionalities of the language

2024-08-16 16:23 UTC, merged