EN-80: Set and see vacations per employee per year
entropy-code/entropay-employees pull request #69
Opened 2023-06-23 14:27 UTC by FacuOrellana

# Description :pencil:

New vacations entity and table. Permissions updated for dev, HR manager and admin role.

## Link to ticket :link:

https://entropyteam.atlassian.net/browse/EN-80

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? :microscope:
Manual testing

Vacation table
![image](https://github.com/entropy-code/entropay-employees/assets/70980835/82fdc939-08d6-4714-882b-0250cb3c6a1c)

2023-06-23 16:32 UTC, agustinb4 requested changes

2023-06-23 16:32 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/controllers/VacationController.java
> +@Secured({ROLE_MANAGER_HR})
Let's allow Admins and developers to use this endpoint

2023-06-23 16:32 UTC, agustinb4 commented on src/main/java/com/entropyteam/entropay/employees/dtos/VacationDto.java
> +                            Integer debit,
Should we check for null?

2023-06-27 16:30 UTC, agustinb4 approved these changes
Looks good!

2023-06-28 12:16 UTC, FedericoA15 commented
good job

2023-06-30 14:35 UTC, merged